name:          APG Coding standards
description:   Standards for developing contributiong HTML, CSS, and JavaScript to W3 WAI-ARIA APG.
url:           http://codeguide.co

markdown:      rdiscount
permalink:     pretty
pygments:      true
